---
title: "Separating multiple choice"
output: html_document
date: "2022-10-24"
---

This is needed for Part C)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
```

## Toy Dataset

```{r}
device_ownership <- tribble( 
    ~name, ~devices_owned,  
    "Charlie", "Smart TV, Cell phone",  
    "Mohammad", "Cell phone",  
    "Christina", "Smart TV, Games Console, Cell phone")
device_ownership
```

Let's separate that column into multiple observations!

```{r}
device_ownership %>% 
  separate_rows(devices_owned,
                sep = ", ") %>% 
  count(devices_owned)
```




## Real survey dataset

- Separate out the values in the Q2 column
- Use count() to count observations
- Make an ordered bar chart with {ggplot2}, you need fct_reorder() for the factors stuff.

```{r}
qualtrics_data <- read_csv("https://raw.githubusercontent.com/charliejhadley/eng7218_data-science-for-healthcare-applications_bcu-masters/main/static/datasets/qualtrics-data.csv")
```

```{r}
qualtrics_data %>% 
  separate_rows(Q2,
                sep = ",") %>% 
  count(Q2) %>% 
  mutate(Q2 = fct_reorder(Q2, n)) %>% 
  ggplot() +
  aes(x = n,
      y = Q2) +
  geom_col()
```



